### Install chardet library to detect the encoding of the dataset.

### This helps us automatically identify the correct encoding form

### Using the correct encoding ensures that the data is read properly (avoid Unicode errors or corrupted text)

### This step improves data quality and helps achieve better model performance.

In [2]:
! pip install chardet

Defaulting to user installation because normal site-packages is not writeable


In [3]:
from webencodings import Encoding

import chardet
import pandas as pd

with open("spam.csv","rb") as data:
    kind_of_encoding = chardet.detect(data.read())['encoding']



df = pd.read_csv("spam.csv", encoding= kind_of_encoding)
print(kind_of_encoding)


iso8859-15


In [4]:
df.head(15)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
5,spam,FreeMsg Hey there darling it's been 3 week's n...,NaN,NaN,NaN
6,ham,Even my brother is not like to speak with me. ...,NaN,NaN,NaN
7,ham,As per your request 'Melle Melle (Oru Minnamin...,NaN,NaN,NaN
8,spam,WINNER!! As a valued network customer you have...,NaN,NaN,NaN
9,spam,Had your mobile 11 months or more? U R entitle...,NaN,NaN,NaN


In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str  
 1   v2          5572 non-null   str  
 2   Unnamed: 2  50 non-null     str  
 3   Unnamed: 3  12 non-null     str  
 4   Unnamed: 4  6 non-null      str  
dtypes: str(5)
memory usage: 217.8 KB


In [6]:
df.isnull().count()

v1            5572
v2            5572
Unnamed: 2    5572
Unnamed: 3    5572
Unnamed: 4    5572
dtype: int64

### Remove unnecessary "Unnamed" columns created due to empty columns in CSV.
### These columns contain no useful information for the model.

## to drop all columns prefix "Unnamed"         -->  df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [7]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [8]:
df.head(15)

,v1,v2
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
5,spam,FreeMsg Hey there darling it's been 3 week's n...
6,ham,Even my brother is not like to speak with me. ...
7,ham,As per your request 'Melle Melle (Oru Minnamin...
8,spam,WINNER!! As a valued network customer you have...
9,spam,Had your mobile 11 months or more? U R entitle...


In [9]:
df.columns = ['label', 'message']
df.head(15)

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
5,spam,FreeMsg Hey there darling it's been 3 week's n...
6,ham,Even my brother is not like to speak with me. ...
7,ham,As per your request 'Melle Melle (Oru Minnamin...
8,spam,WINNER!! As a valued network customer you have...
9,spam,Had your mobile 11 months or more? U R entitle...


In [10]:
import re

def clean_text(text):

    text = text.lower()                             # all letter small

    text = re.sub(r'http\S+', '', text)             #remove links 

    text = re.sub(r'\d+', '', text)                 #remove numbers 

    text = re.sub(r"[^\w\s']", '', text)             #remove not letter, numbers and spase and '  (\w\s = \W)

    text = re.sub(r'\s+', ' ', text).strip()        #remove Extra Space 

    return text


In [11]:
df["clean_message"] = df["message"].apply(clean_text)
df.head(15)

,label,message,clean_message
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in a wkly comp to win fa cup final ...
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i don't think he goes to usf he lives arou...
5,spam,FreeMsg Hey there darling it's been 3 week's n...,freemsg hey there darling it's been week's now...
6,ham,Even my brother is not like to speak with me. ...,even my brother is not like to speak with me t...
7,ham,As per your request 'Melle Melle (Oru Minnamin...,as per your request 'melle melle oru minnaminu...
8,spam,WINNER!! As a valued network customer you have...,winner as a valued network customer you have b...
9,spam,Had your mobile 11 months or more? U R entitle...,had your mobile months or more u r entitled to...


### Now we do Tokenization 

In [12]:
! pip install nltk

Defaulting to user installation because normal site-packages is not writeable


In [13]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('punkt_tab')
df["word_token"] = df["clean_message"].apply(word_tokenize)
df.head(15)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


,label,message,clean_message,word_token
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...,"[go, until, jurong, point, crazy, available, o..."
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni,"[ok, lar, joking, wif, u, oni]"
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in a wkly comp to win fa cup final ...,"[free, entry, in, a, wkly, comp, to, win, fa, ..."
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say,"[u, dun, say, so, early, hor, u, c, already, t..."
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i don't think he goes to usf he lives arou...,"[nah, i, do, n't, think, he, goes, to, usf, he..."
5,spam,FreeMsg Hey there darling it's been 3 week's n...,freemsg hey there darling it's been week's now...,"[freemsg, hey, there, darling, it, 's, been, w..."
6,ham,Even my brother is not like to speak with me. ...,even my brother is not like to speak with me t...,"[even, my, brother, is, not, like, to, speak, ..."
7,ham,As per your request 'Melle Melle (Oru Minnamin...,as per your request 'melle melle oru minnaminu...,"[as, per, your, request, 'melle, melle, oru, m..."
8,spam,WINNER!! As a valued network customer you have...,winner as a valued network customer you have b...,"[winner, as, a, valued, network, customer, you..."
9,spam,Had your mobile 11 months or more? U R entitle...,had your mobile months or more u r entitled to...,"[had, your, mobile, months, or, more, u, r, en..."


### part of stop word removal

In [14]:
from nltk.corpus import stopwords
nltk.download("stopwords")
stop_words = set(stopwords.words("english"))
print(stop_words)



{'wouldn', "hadn't", 'i', 'our', 'them', 'hadn', 'the', 'won', 'nor', "aren't", 'there', 'more', 'has', 't', 'during', "we'd", 'from', 'shan', 'can', 'hers', 'ours', 'out', "she's", 'over', 'because', 'does', 'his', 'haven', 'once', 'of', 'you', 'those', 'then', "you've", 'these', 'between', 'my', 'couldn', 'few', 'should', 'weren', 'or', 'same', 'on', "they'll", 'not', "should've", 'for', 'have', "i'd", 'they', 've', 'if', "shan't", 'any', "it'd", 'again', 'be', 'didn', 'down', 'been', "won't", 'both', 'most', "mustn't", 'as', "don't", "he's", "i've", "he'll", "i'll", 'which', 'with', 'having', 'just', 'under', 'her', "you'll", "they're", 'to', 'are', 'aren', 'doing', 'yourself', 'but', 'a', "it's", 'had', 'here', 'in', "you'd", 'too', 'how', 'themselves', 'she', 'isn', 'shouldn', 'he', 'at', 'were', 'after', 'itself', "she'll", 'than', "wasn't", 'is', "doesn't", 'about', "shouldn't", 'mightn', 'below', 're', 'o', "he'd", "weren't", 'your', "needn't", 'myself', 'ourselves', 'theirs', 

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [15]:
df["word_token"] = df["word_token"].apply(
    lambda words: [word for word in words if word not in stop_words])
df.head(15)

,label,message,clean_message,word_token
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...,"[go, jurong, point, crazy, available, bugis, n..."
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni,"[ok, lar, joking, wif, u, oni]"
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in a wkly comp to win fa cup final ...,"[free, entry, wkly, comp, win, fa, cup, final,..."
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say,"[u, dun, say, early, hor, u, c, already, say]"
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i don't think he goes to usf he lives arou...,"[nah, n't, think, goes, usf, lives, around, th..."
5,spam,FreeMsg Hey there darling it's been 3 week's n...,freemsg hey there darling it's been week's now...,"[freemsg, hey, darling, 's, week, 's, word, ba..."
6,ham,Even my brother is not like to speak with me. ...,even my brother is not like to speak with me t...,"[even, brother, like, speak, treat, like, aids..."
7,ham,As per your request 'Melle Melle (Oru Minnamin...,as per your request 'melle melle oru minnaminu...,"[per, request, 'melle, melle, oru, minnaminung..."
8,spam,WINNER!! As a valued network customer you have...,winner as a valued network customer you have b...,"[winner, valued, network, customer, selected, ..."
9,spam,Had your mobile 11 months or more? U R entitle...,had your mobile months or more u r entitled to...,"[mobile, months, u, r, entitled, update, lates..."


### POS Tagging assigns a grammatical role (noun, verb, adjective, etc.)
### to each word, helping NLP systems better understand sentence structure
### and word meaning based on context.



In [16]:
import nltk

nltk.download("averaged_perceptron_tagger_eng")

from nltk import pos_tag
df["pos_tag"] = df["word_token"].apply(pos_tag)
df.head(15)

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


,label,message,clean_message,word_token,pos_tag
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...,"[go, jurong, point, crazy, available, bugis, n...","[(go, VB), (jurong, JJ), (point, NN), (crazy, ..."
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni,"[ok, lar, joking, wif, u, oni]","[(ok, JJ), (lar, JJ), (joking, NN), (wif, NN),..."
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in a wkly comp to win fa cup final ...,"[free, entry, wkly, comp, win, fa, cup, final,...","[(free, JJ), (entry, NN), (wkly, VBD), (comp, ..."
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say,"[u, dun, say, early, hor, u, c, already, say]","[(u, JJ), (dun, NNS), (say, VBP), (early, JJ),..."
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i don't think he goes to usf he lives arou...,"[nah, n't, think, goes, usf, lives, around, th...","[(nah, JJ), (n't, RB), (think, VB), (goes, VBZ..."
5,spam,FreeMsg Hey there darling it's been 3 week's n...,freemsg hey there darling it's been week's now...,"[freemsg, hey, darling, 's, week, 's, word, ba...","[(freemsg, NN), (hey, NN), (darling, VBG), ('s..."
6,ham,Even my brother is not like to speak with me. ...,even my brother is not like to speak with me t...,"[even, brother, like, speak, treat, like, aids...","[(even, RB), (brother, RBR), (like, IN), (spea..."
7,ham,As per your request 'Melle Melle (Oru Minnamin...,as per your request 'melle melle oru minnaminu...,"[per, request, 'melle, melle, oru, minnaminung...","[(per, IN), (request, NN), ('melle, CD), (mell..."
8,spam,WINNER!! As a valued network customer you have...,winner as a valued network customer you have b...,"[winner, valued, network, customer, selected, ...","[(winner, NN), (valued, VBN), (network, NN), (..."
9,spam,Had your mobile 11 months or more? U R entitle...,had your mobile months or more u r entitled to...,"[mobile, months, u, r, entitled, update, lates...","[(mobile, JJ), (months, NNS), (u, JJ), (r, NN)..."


In [17]:
from nltk.corpus import wordnet

def get_wordnet_pos(tag):

    if tag.startswith("J"):
        return wordnet.ADJ

    elif tag.startswith("V"):
        return wordnet.VERB

    elif tag.startswith("N"):
        return wordnet.NOUN

    elif tag.startswith("R"):
        return wordnet.ADV

    else:
        return wordnet.NOUN

### now we apply stemming and lemmatiztion on tokens 

In [18]:
# stemming 
from nltk import PorterStemmer
stemmer = PorterStemmer()
df["stemmed_tokens"] = df["word_token"].apply(
    lambda words : [stemmer.stem(word) for word in words]
)
df.head(15)

,label,message,clean_message,word_token,pos_tag,stemmed_tokens
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...,"[go, jurong, point, crazy, available, bugis, n...","[(go, VB), (jurong, JJ), (point, NN), (crazy, ...","[go, jurong, point, crazi, avail, bugi, n, gre..."
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni,"[ok, lar, joking, wif, u, oni]","[(ok, JJ), (lar, JJ), (joking, NN), (wif, NN),...","[ok, lar, joke, wif, u, oni]"
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in a wkly comp to win fa cup final ...,"[free, entry, wkly, comp, win, fa, cup, final,...","[(free, JJ), (entry, NN), (wkly, VBD), (comp, ...","[free, entri, wkli, comp, win, fa, cup, final,..."
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say,"[u, dun, say, early, hor, u, c, already, say]","[(u, JJ), (dun, NNS), (say, VBP), (early, JJ),...","[u, dun, say, earli, hor, u, c, alreadi, say]"
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i don't think he goes to usf he lives arou...,"[nah, n't, think, goes, usf, lives, around, th...","[(nah, JJ), (n't, RB), (think, VB), (goes, VBZ...","[nah, n't, think, goe, usf, live, around, though]"
5,spam,FreeMsg Hey there darling it's been 3 week's n...,freemsg hey there darling it's been week's now...,"[freemsg, hey, darling, 's, week, 's, word, ba...","[(freemsg, NN), (hey, NN), (darling, VBG), ('s...","[freemsg, hey, darl, 's, week, 's, word, back,..."
6,ham,Even my brother is not like to speak with me. ...,even my brother is not like to speak with me t...,"[even, brother, like, speak, treat, like, aids...","[(even, RB), (brother, RBR), (like, IN), (spea...","[even, brother, like, speak, treat, like, aid,..."
7,ham,As per your request 'Melle Melle (Oru Minnamin...,as per your request 'melle melle oru minnaminu...,"[per, request, 'melle, melle, oru, minnaminung...","[(per, IN), (request, NN), ('melle, CD), (mell...","[per, request, 'mell, mell, oru, minnaminungin..."
8,spam,WINNER!! As a valued network customer you have...,winner as a valued network customer you have b...,"[winner, valued, network, customer, selected, ...","[(winner, NN), (valued, VBN), (network, NN), (...","[winner, valu, network, custom, select, receiv..."
9,spam,Had your mobile 11 months or more? U R entitle...,had your mobile months or more u r entitled to...,"[mobile, months, u, r, entitled, update, lates...","[(mobile, JJ), (months, NNS), (u, JJ), (r, NN)...","[mobil, month, u, r, entitl, updat, latest, co..."


In [19]:
#Lemmetizer 
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download("wordnet")

lemmetizer = WordNetLemmatizer()

df["lemmetized_tokens"] = df["pos_tag"].apply(
    lambda words :
      [lemmetizer.lemmatize(word,get_wordnet_pos(tag)) for word,tag in words]
)
df.head(15)


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


,label,message,clean_message,word_token,pos_tag,stemmed_tokens,lemmetized_tokens
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...,"[go, jurong, point, crazy, available, bugis, n...","[(go, VB), (jurong, JJ), (point, NN), (crazy, ...","[go, jurong, point, crazi, avail, bugi, n, gre...","[go, jurong, point, crazy, available, bugis, n..."
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni,"[ok, lar, joking, wif, u, oni]","[(ok, JJ), (lar, JJ), (joking, NN), (wif, NN),...","[ok, lar, joke, wif, u, oni]","[ok, lar, joking, wif, u, oni]"
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in a wkly comp to win fa cup final ...,"[free, entry, wkly, comp, win, fa, cup, final,...","[(free, JJ), (entry, NN), (wkly, VBD), (comp, ...","[free, entri, wkli, comp, win, fa, cup, final,...","[free, entry, wkly, comp, win, fa, cup, final,..."
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say,"[u, dun, say, early, hor, u, c, already, say]","[(u, JJ), (dun, NNS), (say, VBP), (early, JJ),...","[u, dun, say, earli, hor, u, c, alreadi, say]","[u, dun, say, early, hor, u, c, already, say]"
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i don't think he goes to usf he lives arou...,"[nah, n't, think, goes, usf, lives, around, th...","[(nah, JJ), (n't, RB), (think, VB), (goes, VBZ...","[nah, n't, think, goe, usf, live, around, though]","[nah, n't, think, go, usf, life, around, though]"
5,spam,FreeMsg Hey there darling it's been 3 week's n...,freemsg hey there darling it's been week's now...,"[freemsg, hey, darling, 's, week, 's, word, ba...","[(freemsg, NN), (hey, NN), (darling, VBG), ('s...","[freemsg, hey, darl, 's, week, 's, word, back,...","[freemsg, hey, darling, 's, week, 's, word, ba..."
6,ham,Even my brother is not like to speak with me. ...,even my brother is not like to speak with me t...,"[even, brother, like, speak, treat, like, aids...","[(even, RB), (brother, RBR), (like, IN), (spea...","[even, brother, like, speak, treat, like, aid,...","[even, brother, like, speak, treat, like, aid,..."
7,ham,As per your request 'Melle Melle (Oru Minnamin...,as per your request 'melle melle oru minnaminu...,"[per, request, 'melle, melle, oru, minnaminung...","[(per, IN), (request, NN), ('melle, CD), (mell...","[per, request, 'mell, mell, oru, minnaminungin...","[per, request, 'melle, melle, oru, minnaminung..."
8,spam,WINNER!! As a valued network customer you have...,winner as a valued network customer you have b...,"[winner, valued, network, customer, selected, ...","[(winner, NN), (valued, VBN), (network, NN), (...","[winner, valu, network, custom, select, receiv...","[winner, value, network, customer, select, rec..."
9,spam,Had your mobile 11 months or more? U R entitle...,had your mobile months or more u r entitled to...,"[mobile, months, u, r, entitled, update, lates...","[(mobile, JJ), (months, NNS), (u, JJ), (r, NN)...","[mobil, month, u, r, entitl, updat, latest, co...","[mobile, month, u, r, entitle, update, late, c..."


In [21]:
df["final_text"] = df["lemmetized_tokens"].apply(lambda words: " ".join(words))
df.head(5)

,label,message,clean_message,word_token,pos_tag,stemmed_tokens,lemmetized_tokens,final_text
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...,"[go, jurong, point, crazy, available, bugis, n...","[(go, VB), (jurong, JJ), (point, NN), (crazy, ...","[go, jurong, point, crazi, avail, bugi, n, gre...","[go, jurong, point, crazy, available, bugis, n...",go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni,"[ok, lar, joking, wif, u, oni]","[(ok, JJ), (lar, JJ), (joking, NN), (wif, NN),...","[ok, lar, joke, wif, u, oni]","[ok, lar, joking, wif, u, oni]",ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in a wkly comp to win fa cup final ...,"[free, entry, wkly, comp, win, fa, cup, final,...","[(free, JJ), (entry, NN), (wkly, VBD), (comp, ...","[free, entri, wkli, comp, win, fa, cup, final,...","[free, entry, wkly, comp, win, fa, cup, final,...",free entry wkly comp win fa cup final tkts st ...
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say,"[u, dun, say, early, hor, u, c, already, say]","[(u, JJ), (dun, NNS), (say, VBP), (early, JJ),...","[u, dun, say, earli, hor, u, c, alreadi, say]","[u, dun, say, early, hor, u, c, already, say]",u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i don't think he goes to usf he lives arou...,"[nah, n't, think, goes, usf, lives, around, th...","[(nah, JJ), (n't, RB), (think, VB), (goes, VBZ...","[nah, n't, think, goe, usf, live, around, though]","[nah, n't, think, go, usf, life, around, though]",nah n't think go usf life around though


## Spilting data and Models


In [24]:
X = df["final_text"]
y = df["label"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [25]:
# BOW
from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer()

X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

In [26]:
# TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [27]:
ngram = CountVectorizer(ngram_range=(1,2))

X_train_ngram = ngram.fit_transform(X_train)
X_test_ngram = ngram.transform(X_test)

### models and predictions 


### BOW MODELS 

In [35]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train_bow, y_train)



,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [44]:
y_pred_bow = model.predict(X_test_bow)
print(y_pred_bow)

['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']


### TF-IDF Model

In [38]:
from sklearn.naive_bayes import MultinomialNB

model_tfidf = MultinomialNB()

model_tfidf.fit(
    X_train_tfidf,
    y_train
)


,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [40]:
y_pred_tfidf = model_tfidf.predict(X_test_tfidf)
print(y_pred_tfidf)

['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']


### N-GRAM Model

In [41]:
from sklearn.naive_bayes import MultinomialNB

model_tfidf = MultinomialNB()

model_ngram = MultinomialNB()

model_ngram.fit(
    X_train_ngram,
    y_train
)


,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [43]:
y_pred_ngram = model_ngram.predict(X_test_ngram)
print(y_pred_ngram)

['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']


In [46]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

results = {
    "BoW": y_pred_bow,
    "TF-IDF": y_pred_tfidf,
    "N-gram": y_pred_ngram
}


evaluation_results = []


for name, prediction in results.items():

    accuracy = accuracy_score(y_test, prediction)

    precision = precision_score(
        y_test,
        prediction,
        pos_label="spam"
    )

    recall = recall_score(
        y_test,
        prediction,
        pos_label="spam"
    )

    f1 = f1_score(
        y_test,
        prediction,
        pos_label="spam"
    )


    evaluation_results.append({
        "Model": name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1-score": f1
    })

In [47]:
import pandas as pd

results_df = pd.DataFrame(evaluation_results)

results_df

,Model,Accuracy,Precision,Recall,F1-score
0,BoW,0.977578,0.949275,0.879195,0.912892
1,TF-IDF,0.962332,0.990826,0.724832,0.837209
2,N-gram,0.981166,0.984848,0.872483,0.925267


### big problem when email is ham and we predect as spam so the impoetant evaluation i check is "precision" then "recall" to not pass a lot of spam emails 
## so we look to F1-score to balanced between 



# SMS Spam Detection – Project Report
### 1. Introduction
This project builds a text classification system to distinguish spam SMS messages from legitimate ("ham") ones. The pipeline covers data loading, text preprocessing, feature extraction, model training, and evaluation using three different feature representations paired with a Naive Bayes classifier.
### 2. Dataset

Source: spam.csv, 5,572 messages total.
Encoding issue: The raw CSV had an unusual character encoding. The chardet library was used to auto-detect it (ISO-8859-15) before loading with pandas, avoiding Unicode/corruption errors.
Cleanup: The dataset originally had 3 extra unnamed/empty columns (leftover from stray commas in the raw file). These were dropped, leaving two columns, renamed to label (ham/spam) and message (raw SMS text).

### 3. Text Preprocessing
A full NLP preprocessing pipeline was applied to prepare the raw text for modeling:

Text Cleaning (clean_text function):

Lowercased all text
Removed URLs
Removed digits
Removed punctuation/special characters (kept letters, numbers, spaces, apostrophes)
Collapsed extra whitespace


Tokenization: Used NLTK's word_tokenize to split cleaned messages into individual word tokens.
Stopword Removal: Common English stopwords (e.g., "the", "is", "and") were filtered out using NLTK's stopword list, since they carry little discriminative value for spam detection.
POS Tagging: Each token was tagged with its part of speech (noun, verb, adjective, adverb) using NLTK's averaged perceptron tagger. This was a necessary step to enable accurate lemmatization (lemmatization needs to know a word's grammatical role to reduce it correctly).
Stemming vs. Lemmatization:

Stemming (Porter Stemmer) was applied to reduce words to their root form (fast but crude, e.g., "studies" → "studi").
Lemmatization (WordNet Lemmatizer, using the POS tags from step 4) was applied to reduce words to their dictionary base form (more linguistically accurate, e.g., "studies" → "study").
The lemmatized tokens were joined back into a final cleaned string (final_text) and used as the input for modeling.



### 4. Train/Test Split
Data was split 80/20 into training and test sets, with stratification on the label to preserve the spam/ham ratio in both sets (important given the class imbalance typical of this dataset).
### 5. Feature Extraction
Three different text vectorization methods were used to convert final_text into numerical features:
MethodDescriptionBag of Words (BoW)Counts raw word frequency per message, ignoring word order/context.TF-IDFWeights word counts by how unique/informative a word is across the whole corpus, downweighting very common words.N-gram (1,2)Extends BoW to include both single words (unigrams) and word pairs (bigrams), capturing some local word order/context.
### 6. Modeling
A Multinomial Naive Bayes classifier — well-suited to word-count-style features — was trained separately on each of the three feature sets (BoW, TF-IDF, N-gram), producing three independent models.
### 7. Evaluation Results
ModelAccuracyPrecisionRecallF1-scoreBoW0.97760.94930.87920.9129TF-IDF0.96230.99080.72480.8372N-gram0.98120.98480.87250.9253
Metrics used:

Accuracy – overall correctness across all predictions.
Precision (spam as positive class) – of all messages predicted as spam, how many actually were spam. High precision means fewer legitimate messages wrongly flagged as spam.
Recall – of all actual spam messages, how many were correctly caught.
F1-score – harmonic mean of precision and recall, giving a balanced measure.

### 8. Discussion

Since misclassifying a legitimate ("ham") message as spam is more costly than missing a spam message (a real email/SMS getting blocked is a bigger problem than an occasional spam getting through), precision was prioritized as the primary metric, followed by recall.
TF-IDF achieved the highest precision (0.99) but the lowest recall (0.72), meaning it was very conservative — it rarely mislabeled ham as spam, but missed more actual spam messages.
N-gram gave the best overall balance, with the highest accuracy (0.981) and highest F1-score (0.925), combining strong precision (0.985) with better recall (0.873) than TF-IDF — likely because bigrams captured short spam phrases (e.g., "free entry", "call now") that unigrams alone missed.
BoW performed reasonably well but was outperformed by N-gram in every metric.

### 9. Conclusion
The N-gram (unigram + bigram) representation with Multinomial Naive Bayes was the best-performing model overall, offering the strongest balance between catching spam (recall) and avoiding false positives on legitimate messages (precision), as reflected in its top F1-score of 0.925.